#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp 0.orig 0 -R

application=$(getApplication)

runApplication blockMesh
runApplication setAlphaVofi
# runApplication $application
#------------------------------------------------------------------------------
