#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
# . ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

set -x

#------------------------------------------------------------------------------

wmake libso alphaImplicitFunctions
wmake $targetType

#------------------------------------------------------------------------------
